/**
 * ArbiterCouncil ABI.
 *
 * Auto-generated by packages/shared/scripts/extract-abis.ts.
 * DO NOT EDIT BY HAND. Re-run `pnpm --filter @kanbantic/shared extract-abis`
 * after every contract change in packages/contracts/.
 */
export const ArbiterCouncilAbi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "arbiters_",
        type: "address[]",
        internalType: "address[]",
      },
      {
        name: "quorum_",
        type: "uint8",
        internalType: "uint8",
      },
      {
        name: "bountyBoard_",
        type: "address",
        internalType: "contract IBountyBoard",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "arbiters",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address[]",
        internalType: "address[]",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "bountyBoard",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IBountyBoard",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "decisionExecuted",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "execute",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "isArbiter",
    inputs: [
      {
        name: "candidate",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "quorum",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint8",
        internalType: "uint8",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "vote",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "refund",
        type: "bool",
        internalType: "bool",
      },
      {
        name: "reasonRef",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "voteCounts",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "acceptCount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "refundCount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "Executed",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "refunded",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Voted",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "arbiter",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "refund",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
      {
        name: "reasonRef",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "AlreadyExecuted",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "AlreadyVoted",
    inputs: [
      {
        name: "arbiter",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "DuplicateArbiter",
    inputs: [
      {
        name: "arbiter",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "InvalidQuorum",
    inputs: [],
  },
  {
    type: "error",
    name: "NotArbiter",
    inputs: [
      {
        name: "caller",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "QuorumNotMet",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "ZeroAddress",
    inputs: [],
  },
  {
    type: "error",
    name: "ZeroArbiter",
    inputs: [],
  },
] as const;

export type ArbiterCouncilAbi = typeof ArbiterCouncilAbi;
