/**
 * BountyBoard ABI.
 *
 * Auto-generated by packages/shared/scripts/extract-abis.ts.
 * DO NOT EDIT BY HAND. Re-run `pnpm --filter @kanbantic/shared extract-abis`
 * after every contract change in packages/contracts/.
 */
export const BountyBoardAbi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "workspaceRegistry_",
        type: "address",
        internalType: "contract IWorkspaceRegistry",
      },
      {
        name: "orbitportOracle_",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "accept",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "bountyOf",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct IBountyBoard.Bounty",
        components: [
          {
            name: "poster",
            type: "address",
            internalType: "address",
          },
          {
            name: "capabilityFilter",
            type: "string",
            internalType: "string",
          },
          {
            name: "reward",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "descriptionRef",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "expiresAt",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "claimWindowBlocks",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "claimWindowStartBlock",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "status",
            type: "uint8",
            internalType: "enum IBountyBoard.Status",
          },
          {
            name: "claimerNode",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "submissionRef",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "workspaceNode",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "arbiterCouncil",
            type: "address",
            internalType: "address",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claim",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "agentNode",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "commitClaim",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "commitment",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "expire",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "finalizeFairClaim",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "ctrngDraw",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "nextId",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "orbitportOracle",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "post",
    inputs: [
      {
        name: "capabilityFilter",
        type: "string",
        internalType: "string",
      },
      {
        name: "reward",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "descriptionRef",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "expiresAt",
        type: "uint64",
        internalType: "uint64",
      },
      {
        name: "claimWindowBlocks",
        type: "uint32",
        internalType: "uint32",
      },
      {
        name: "workspaceNode",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "arbiterCouncil",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "posterOf",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "reject",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "reasonRef",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revealClaim",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "nonce",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "agentNode",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "settleDispute",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "refund",
        type: "bool",
        internalType: "bool",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "statusOf",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint8",
        internalType: "enum IBountyBoard.Status",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "submit",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "proofRef",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "workspaceRegistry",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IWorkspaceRegistry",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "BountyAccepted",
    inputs: [
      {
        name: "id",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "payee",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BountyClaimCommitted",
    inputs: [
      {
        name: "id",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "committer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "commitment",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BountyClaimFinalized",
    inputs: [
      {
        name: "id",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "pickedAddress",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "ctrngDraw",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BountyClaimed",
    inputs: [
      {
        name: "id",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "agentNode",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "claimer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BountyExpired",
    inputs: [
      {
        name: "id",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BountyPosted",
    inputs: [
      {
        name: "id",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "poster",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "workspaceNode",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "capabilityFilter",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "reward",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "descriptionRef",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "expiresAt",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
      {
        name: "claimWindowBlocks",
        type: "uint32",
        indexed: false,
        internalType: "uint32",
      },
      {
        name: "arbiterCouncil",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BountyRejected",
    inputs: [
      {
        name: "id",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "reasonRef",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BountySettled",
    inputs: [
      {
        name: "id",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "refunded",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BountySubmitted",
    inputs: [
      {
        name: "id",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "proofRef",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "BadStatus",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "ClaimWindowClosed",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "ClaimWindowOpen",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "CommitmentMismatch",
    inputs: [],
  },
  {
    type: "error",
    name: "ExpiryInPast",
    inputs: [],
  },
  {
    type: "error",
    name: "NoArbiterCouncil",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "NoCommitters",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "NotArbiterCouncil",
    inputs: [
      {
        name: "caller",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "NotClaimer",
    inputs: [
      {
        name: "caller",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "NotOrbitportOracle",
    inputs: [
      {
        name: "caller",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "NotPickedClaimant",
    inputs: [
      {
        name: "caller",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "NotPoster",
    inputs: [
      {
        name: "caller",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "NotWorkspaceMember",
    inputs: [
      {
        name: "workspaceNode",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "caller",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "NotYetExpired",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "ReentrancyGuardReentrantCall",
    inputs: [],
  },
  {
    type: "error",
    name: "RewardValueMismatch",
    inputs: [
      {
        name: "reward",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "sent",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "WrongClaimMode",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "ZeroAddress",
    inputs: [],
  },
  {
    type: "error",
    name: "ZeroAgentNode",
    inputs: [],
  },
  {
    type: "error",
    name: "ZeroReward",
    inputs: [],
  },
] as const;

export type BountyBoardAbi = typeof BountyBoardAbi;
