/**
 * ReputationAttestor ABI.
 *
 * Auto-generated by packages/shared/scripts/extract-abis.ts.
 * DO NOT EDIT BY HAND. Re-run `pnpm --filter @kanbantic/shared extract-abis`
 * after every contract change in packages/contracts/.
 */
export const ReputationAttestorAbi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "bountyBoard_",
        type: "address",
        internalType: "contract IBountyBoard",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "attest",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "agentNode",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "score",
        type: "uint8",
        internalType: "uint8",
      },
      {
        name: "commentRef",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "bountyBoard",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IBountyBoard",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasAttested",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "reviewer",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "Attested",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "agentNode",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "reviewer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "score",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
      {
        name: "commentRef",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "AlreadyAttested",
    inputs: [
      {
        name: "bountyId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "reviewer",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "InvalidScore",
    inputs: [
      {
        name: "score",
        type: "uint8",
        internalType: "uint8",
      },
    ],
  },
  {
    type: "error",
    name: "NotBountyPoster",
    inputs: [
      {
        name: "caller",
        type: "address",
        internalType: "address",
      },
      {
        name: "expected",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "ZeroAddress",
    inputs: [],
  },
] as const;

export type ReputationAttestorAbi = typeof ReputationAttestorAbi;
