/**
 * WorkspaceRegistry ABI.
 *
 * Auto-generated by packages/shared/scripts/extract-abis.ts.
 * DO NOT EDIT BY HAND. Re-run `pnpm --filter @kanbantic/shared extract-abis`
 * after every contract change in packages/contracts/.
 */
export const WorkspaceRegistryAbi = [
  {
    type: "function",
    name: "addMember",
    inputs: [
      {
        name: "wsNode",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "member",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "adminOf",
    inputs: [
      {
        name: "wsNode",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createWorkspace",
    inputs: [
      {
        name: "parentNode",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "initialMembers",
        type: "address[]",
        internalType: "address[]",
      },
    ],
    outputs: [
      {
        name: "wsNode",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "exists",
    inputs: [
      {
        name: "wsNode",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isMember",
    inputs: [
      {
        name: "wsNode",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "user",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "membersOf",
    inputs: [
      {
        name: "wsNode",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "",
        type: "address[]",
        internalType: "address[]",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "removeMember",
    inputs: [
      {
        name: "wsNode",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "member",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferAdmin",
    inputs: [
      {
        name: "wsNode",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "newAdmin",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "AdminTransferred",
    inputs: [
      {
        name: "wsNode",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "oldAdmin",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newAdmin",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MemberAdded",
    inputs: [
      {
        name: "wsNode",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "member",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MemberRemoved",
    inputs: [
      {
        name: "wsNode",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "member",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "WorkspaceCreated",
    inputs: [
      {
        name: "wsNode",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "parentNode",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "admin",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "AlreadyMember",
    inputs: [
      {
        name: "member",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "NotAdmin",
    inputs: [
      {
        name: "caller",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "NotMember",
    inputs: [
      {
        name: "member",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "WorkspaceAlreadyExists",
    inputs: [
      {
        name: "wsNode",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "WorkspaceNotFound",
    inputs: [
      {
        name: "wsNode",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "ZeroAddress",
    inputs: [],
  },
  {
    type: "error",
    name: "ZeroParent",
    inputs: [],
  },
] as const;

export type WorkspaceRegistryAbi = typeof WorkspaceRegistryAbi;
