/**
 * Reads forge artefacts under packages/contracts/out/ and emits
 * `as const` typed ABI exports under src/abi/.
 *
 * Idempotent: running twice produces identical files. Any drift between
 * the contract bytecode and the emitted ABI is captured in `git diff`.
 *
 * The emitted files are formatted with prettier so that the husky pre-commit
 * hook (which also runs prettier on staged .ts files) is a no-op on top of
 * the script output. Without this, the script would emit JSON-style
 * `"key": value` and prettier would rewrite to JS-object-literal `key: value`,
 * making subsequent re-runs produce a diff.
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, "../../..");
const FORGE_OUT = join(REPO_ROOT, "packages/contracts/out");
const ABI_DIR = join(REPO_ROOT, "packages/shared/src/abi");
const PRETTIER_BIN = join(REPO_ROOT, "node_modules/.bin/prettier");

const CONTRACTS = [
  "AgentRegistry",
  "AgentVenture",
  "ArbiterCouncil",
  "BountyBoard",
  "ReputationAttestor",
  "WorkspaceRegistry",
] as const;

type AbiEntry = Record<string, unknown>;

function readForgeArtifact(contract: string): { abi: AbiEntry[] } {
  const artefactPath = join(FORGE_OUT, `${contract}.sol`, `${contract}.json`);
  if (!existsSync(artefactPath)) {
    throw new Error(
      `Forge artefact not found: ${artefactPath}. Did you run 'forge build' in packages/contracts/?`,
    );
  }
  const raw = readFileSync(artefactPath, "utf8");
  const parsed = JSON.parse(raw) as { abi: AbiEntry[] };
  if (!Array.isArray(parsed.abi)) {
    throw new Error(`Malformed forge artefact (no abi array): ${artefactPath}`);
  }
  return parsed;
}

function formatWithPrettier(filePath: string): void {
  if (!existsSync(PRETTIER_BIN)) {
    throw new Error(
      `prettier not found at ${PRETTIER_BIN}. Run 'pnpm install' at the repo root first.`,
    );
  }
  execFileSync(PRETTIER_BIN, ["--write", "--log-level", "warn", filePath], {
    cwd: REPO_ROOT,
    stdio: ["ignore", "inherit", "inherit"],
  });
}

function emitContractFile(contract: string, abi: AbiEntry[]): void {
  const constName = `${contract}Abi`;
  const body = JSON.stringify(abi, null, 2);
  const out = `/**
 * ${contract} ABI.
 *
 * Auto-generated by packages/shared/scripts/extract-abis.ts.
 * DO NOT EDIT BY HAND. Re-run \`pnpm --filter @kanbantic/shared extract-abis\`
 * after every contract change in packages/contracts/.
 */
export const ${constName} = ${body} as const;

export type ${constName} = typeof ${constName};
`;
  const outPath = join(ABI_DIR, `${contract}.ts`);
  writeFileSync(outPath, out);
  formatWithPrettier(outPath);
  console.log(`wrote ${outPath} (${String(abi.length)} entries)`);
}

function emitIndex(): void {
  const lines = [
    "/**",
    " * Auto-generated by packages/shared/scripts/extract-abis.ts.",
    " * DO NOT EDIT BY HAND.",
    " */",
    "",
    ...CONTRACTS.map((c) => `export { ${c}Abi, type ${c}Abi as ${c}AbiType } from "./${c}.js";`),
    "",
  ];
  const outPath = join(ABI_DIR, "index.ts");
  writeFileSync(outPath, lines.join("\n"));
  formatWithPrettier(outPath);
  console.log(`wrote ${outPath}`);
}

function main(): void {
  if (!existsSync(ABI_DIR)) {
    mkdirSync(ABI_DIR, { recursive: true });
  }
  for (const contract of CONTRACTS) {
    const { abi } = readForgeArtifact(contract);
    emitContractFile(contract, abi);
  }
  emitIndex();
}

main();
